spring:
  application:
    name: dolphin-gateway
  config:
    import: classpath:cache.yml,classpath:config.yml,classpath:limiter.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
server:
  port: 8081
